create table USER(
	USER_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (USER_ID),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100),
    SALT VARCHAR(100),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    DATE_OF_REGISTRATION DATETIME,
    USER_UUID VARCHAR(100) NOT NULL UNIQUE
);

create table COMPANY(
	COMPANY_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (COMPANY_ID),
    COMPANY_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    STREET_ADDRESS_LINE_1 VARCHAR(100),
    STREET_ADDRESS_LINE_2 VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    ZIP VARCHAR(20),
    USER_UUID VARCHAR(100) NOT NULL,
    FOREIGN KEY (USER_UUID) REFERENCES USER(USER_UUID)
);

create table UNIT_OF_MEASURE(
	UOM_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (UOM_ID),
    UOM_NAME VARCHAR(100),
    SYMBOL VARCHAR(20),
    PRECISION_VALUE INT,
    USER_UUID VARCHAR(100) NOT NULL,
    FOREIGN KEY (USER_UUID) REFERENCES USER(USER_UUID)
)